### ISSUE TITLE
ボタンを押した時に願望や交際などテーマと占い内容を画面に表示する

### ISSUE THREAD

**Issue by arith-alexander** [arith-alexander/vpc_docker#17]
テーマは三つ。それぞれパターン四つ

・願望
　・超吉
　・大吉
　・中吉
　・吉
・交際
　・超吉
　・大吉
　・中吉
　・吉
・病気
　・超吉
　・大吉
　・中吉
　・吉

対応内容
・fortuneとthemeテーブルの作成
・占い内容を書いてDBに保存
・ボタンを押した時にテーマと占い内容を画面に表示する

**Comment by arith-alexander** [comment]
着手します

**Comment by arith-k-saito** [comment]
https://github.com/arith-alexander/vpc_docker/pull/23
にて対応済み
