### ISSUE TITLE
ボタンを押した時にくじの内容を画面に表示する

### ISSUE THREAD

**Issue by arith-k-saito** [arith-alexander/vpc_docker#4]

**Comment by arith-k-saito** [comment]
kuzi_patternとkuzi_historyのデータを全部取得する

kuzi_patternのmaxからkuzi_historyを引いた残りのくじ数を算出する

そこからランダムに抽選

**Comment by arith-k-saito** [comment]
ちゃくしゅします

**Comment by arith-alexander** [comment]
超吉、大吉などパターンを表示するだけ。
願望、交際などテーマは別途issueで対応。

**Comment by arith-alexander** [comment]
https://github.com/arith-alexander/vpc_docker/pull/18 にて対応済み
