### ISSUE TITLE
くじに必要なテーブルをDBに作成する

### ISSUE THREAD

**Issue by arith-k-saito** [arith-alexander/vpc_docker#9]

**Comment by arith-k-saito** [comment]
必要テーブル

・pattern
id
name
max
rest

・history
id
pattern_id
create_date

くじの概要とかは最初はDBに持たない

**Comment by arith-k-saito** [comment]
ちゃくしゅします。

**Comment by arith-alexander** [comment]
https://github.com/arith-alexander/vpc_docker/pull/12 にて対応済み
